name: DragonForgeLastLife
version: '0.0.1'
main: me.quickscythe.paper.ll4el.Initializer
api-version: '1.21'
dependencies:
  server:
    DragonForgeCore:
      load: BEFORE
      required: true
      join-classpath: true


